
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kakitu-prices
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid   # Ensures no concurrent job runs
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kakitu-prices
            image: replaceme
            command: ["/bin/sh", "-c"]
            args: ["kakitu-server -kshs-price-update"]
            env:
              - name: REDIS_HOST
                value: redis.redis
              - name: REDIS_DB
                value: "15"
          restartPolicy: OnFailure
