apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakitu-wallet-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kakitu-wallet-server
  template:
    metadata:
      labels:
        app: kakitu-wallet-server
    spec:
      containers:
      - name: kakitu-wallet-server
        image: replaceme
        command: ["/bin/sh", "-c"]
        args: ["kakitu-server -socket-io"]
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 3000
          name: api
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "10"
          - name: RPC_URL
            value: http://10.7.0.1:7076
          - name: DB_HOST
            value: pg-kakitu.kakitu
          - name: DB_PORT
            value: "5432"
          - name: DB_SSLMODE
            value: disable
          - name: DB_NAME
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: kakitu
                key: db_password
          - name: FCM_API_KEY
            valueFrom:
              secretKeyRef:
                name: kakitu
                key: fcm_api_key
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: kakitu
                key: bpow_key
          - name: WORK_URL
            valueFrom:
              secretKeyRef:
                name: kakitu
                key: work_url
          - name: NODE_WS_URL
            value: ws://10.7.0.1:7078
